### ISSUE TITLE
[adat] handling of type parameters

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [spxbhuhb/adaptive#83]
```kotlin
@Adat
class AutoMetadata<T>(
    val connection: AutoConnectionInfo<T>,
    val removedItems: List<ItemId>,
    val milestone: LamportTimestamp
)
```

Results in:

```text
java.lang.IllegalArgumentException: 'public final class AutoMetadata<T> : R|kotlin/Any|, R|fun/adaptive/adat/AdatClass| {
    public? constructor<T>(connection: AutoConnectionInfo<T>, removedItems: List<ItemId>, milestone: LamportTimestamp): R|fun/adaptive/auto/model/AutoMetadata<T>|
    public? final? val connection: AutoConnectionInfo<T>
    public? final? val removedItems: List<ItemId>
    public? final? val milestone: LamportTimestamp
}
' expects '1' type arguments but type 'fun/adaptive/auto/model/AutoMetadata' has 0 type arguments.
	at org.jetbrains.kotlin.analysis.api.fir.components.KaFirTypeProvider.getSubstitutedSuperTypes(KaFirTypeProvider.kt:299)
	at org.jetbrains.kotlin.analysis.api.fir.components.KaFirTypeProvider.getDirectSuperTypes(KaFirTypeProvider.kt:279)
	at org.jetbrains.kotlin.analysis.api.fir.components.KaFirTypeProvider.allSupertypes$lambda$28$lambda$26(KaFirTypeProvider.kt:322)
	at org.jetbrains.kotlin.util.ContainerUtilsKt$bfs$1.invokeSuspend(containerUtils.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.DropSequence$iterator$1.hasNext(Sequences.kt:508)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at org.jetbrains.kotlin.analysis.api.components.KaTypeProvider.getAllSuperTypes(KaTypeProvider.kt:173)
	at org.jetbrains.kotlin.analysis.api.impl.base.KaBaseSession.getAllSuperTypes(KaBaseSession.kt)
	at org.jetbrains.kotlin.analysis.api.components.KaTypeProvider.getAllSuperTypes$default(KaTypeProvider.kt:172)
	at org.jetbrains.kotlin.idea.base.codeInsight.KotlinNameSuggesterKt.getIterableElementType(KotlinNameSuggester.kt:598)
	at org.jetbrains.kotlin.idea.base.codeInsight.KotlinNameSuggesterKt.access$getIterableElementType(KotlinNameSuggester.kt:1)
	at org.jetbrains.kotlin.idea.base.codeInsight.KotlinNameSuggester$suggestTypeNames$1.invokeSuspend(KotlinNameSuggester.kt:245)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.K2CreateFunctionFromUsageUtil.getExpectedParameterInfo$kotlin_code_insight_k2(K2CreateFunctionFromUsageUtil.kt:166)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.CreateExecutableFromKotlinUsageRequest.computeExpectedParams(CreateExecutableFromKotlinUsageRequest.kt:27)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.CreateExecutableFromKotlinUsageRequest.<init>(CreateExecutableFromKotlinUsageRequest.kt:22)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.CreateMethodFromKotlinUsageRequest.<init>(CreateMethodFromKotlinUsageRequest.kt:29)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.K2CreateFunctionFromUsageBuilder.buildRequests(K2CreateFunctionFromUsageBuilder.kt:81)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.K2CreateFunctionFromUsageBuilder.buildRequestsAndActions$kotlin_code_insight_k2(K2CreateFunctionFromUsageBuilder.kt:55)
	at org.jetbrains.kotlin.idea.k2.codeinsight.quickFixes.createFromUsage.K2CreateFromUsageQuickFixesRegistrar.createFunctionForArgumentTypeMismatch$lambda$0(K2CreateFromUsageQuickFixesRegistrar.kt:22)
	at org.jetbrains.kotlin.idea.codeinsight.api.applicators.fixes.KotlinQuickFixesList$getQuickFixesFor$2.invoke(KotlinQuickFixesList.kt:22)
	at org.jetbrains.kotlin.idea.codeinsight.api.applicators.fixes.KotlinQuickFixesList$getQuickFixesFor$2.invoke(KotlinQuickFixesList.kt:22)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:812)
	at org.jetbrains.kotlin.idea.codeinsight.api.applicators.fixes.KotlinQuickFixesList.getQuickFixesFor(KotlinQuickFixesList.kt:24)
	at org.jetbrains.kotlin.idea.codeinsight.api.applicators.fixes.KotlinQuickFixService.getQuickFixesFor(KotlinQuickFixService.kt:24)
	at org.jetbrains.kotlin.idea.highlighting.KotlinDiagnosticHighlightVisitor.convertToBuilder(KotlinDiagnosticHighlightVisitor.kt:90)
	at org.jetbrains.kotlin.idea.highlighting.KotlinDiagnosticHighlightVisitor.analyzeFile(KotlinDiagnosticHighlightVisitor.kt:68)
	at org.jetbrains.kotlin.idea.highlighting.KotlinDiagnosticHighlightVisitor.analyze(KotlinDiagnosticHighlightVisitor.kt:47)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$4(HighlightVisitorRunner.java:120)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:86)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```

**Comment by toth-istvan-zoltan** [comment]
This actually works (polymorphic).
